dist: trusty
sudo: false

language: node_js
node_js:
  - '10.15.3'

before_install:
  - npm install -g gulp-cli npm@6.12.0 bower

script: gulp build

cache:
  directories:
    - ./node_modules
    - ./bower_components
